name: login_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
assets: 
    - assets/icon_google.png
    # - assets/images/
  
    # - family: Montserrat
    #   fonts: 
    #     - asset: assets/fonts/MontserratRomanExtraBold.ttf
    #       weight: 800
    #     - asset: assets/fonts/MontserratRomanMedium.ttf
    #       weight: 500
    #     - asset: assets/fonts/MontserratRomanBold.ttf
    #       weight: 700
    # - family: Poppins
    #   fonts: 
    #     - asset: assets/fonts/PoppinsSemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/PoppinsRegular.ttf
    #       weight: 400
    #     - asset: assets/fonts/PoppinsBold.ttf
    #       weight: 700
    #     - asset: assets/fonts/PoppinsMedium.ttf
    #       weight: 500

